package uno.idk.model;

/**
 * Created by moham on 6/4/2016.
 */

public class JourneyType {
    //USED WHEN YOU WANT TO GET YOUR BAGS PICKED UP FROM YOUR HOUSE OR HOTEL TO GET DROPPED OFF TO THE AIRPORT
    public static String PLACETOAIRPORT = "PLACETOARIPORT";

    //USED WHEN YOU WANT THE BAGS TO GO FROM THE AIRPORT TO THE HOTEL/YOURHOUSE/ETC -- IMPORTANT: THIS IS FOR WHEN THE USER LEAVES CUSTOMS WITH BAGS AND CHANGES MIND EITHER
    //IN AIRPORT OR IN TERMINAL TUBE STATION
    public static String AIRPORTTOPLACE = "AIRPORTTOPLACE";

    //THIS IS USED WHEN YOU WANT TO TRACK THE BAG AFTER CHECK IN ON IT'S WAY TO THE AIRCRAFT
    public static String CHECKINTOAIRCRAFT = "CHECKINTOAIRCRAFT";

    //THIS IS USED TO TRACK THE ITEM AFTER IT IS OFFLOADED FROM THE PLANE ON ITS WAY TO THE CAROUSEL. THIS WILL BE SHOWN EVEN WHEN THE CUSTOMER ALREADY PAID FOR DELIVERY SERVICE
    public static String AIRCRAFTTOCAROUSEL = "AIRCRAFTTOCAROUSEL";

    //THIS IS A BASIC TRACKING OF THE BAGS PROGRESS THROUGH SECURITY
    public static String CAROUSELTHROUGHSECURITY = "CAROUSELTHROUGHSECURITY";

    //THIS WILL BE USED WHEN SECURITY OR CUSTOMS IS PASSED AT ARRIVAL AIRPORT AND THE ITEM IS IN THE VAN ON ITS WAY TO THE FINAL DESTINATION
    public static String SECURITYPASSEDTOPLACE = "SECURITYPASSEDTOPLACE";

    //THIS WILL BE USED TO INDICATE THAT SECURITY OR CUSTOMS WAS FAILED AND THAT THE BAG HAS TO BE PICKED UP FROM THE AIRPORT
    public static String SECURITYFAILEDTOHOLD = "SECURITYFAILEDTOHOLD";

}
